name: Python Code Formatter
author: Alex Pinches
description: Formats python code

inputs:
        GITHUB_TOKEN:
                description: 'GitHub access token with Repo scope'
                required: true
                default: ${{ github.token }}
        PR_NUMBER:
                description: 'Github PR Number'
                required: true
                default: ${{ github.event.pull_request.number }}

runs:
        using: 'docker'
        image: 'Dockerfile'
branding:
        icon: 'activity'
        color: 'orange'