name: Python & SQL Code Formatter
author: Alex Pinches
description: Formats Python and SQL code

inputs:
        GH_TOKEN:
                description: 'GitHub Token'
                required: true
        PR_NUMBER:
                description: 'PR Number'
                required: true

runs:
        using: 'docker'
        image: 'Dockerfile'
        env:
                DOCKER_BUILDKIT: 1 
branding:
        icon: 'activity'
        color: 'orange'