name: Python Code Formatter
author: Alex Pinches
description: Formats python code

inputs:
        GITHUB_TOKEN:
                description: 'GitHub access token with Repo scope'
                required: true
                default: ${{ github.token }}
        URL:
                description: 'Github comment url'
                required: false
                default: ${{ github.event.pull_request.comments_url }}

runs:
        using: 'docker'
        image: 'Dockerfile'
branding:
        icon: 'activity'
        color: 'orange'