name: Python Code Formatter
author: Alex Pinches
description: Formats python code

inputs:
        GH_TOKEN:
                description: 'GitHub Token'
                required: true
        PR_NUMBER:
                description: 'PR Number'
                required: true

runs:
        using: 'docker'
        image: 'Dockerfile'
branding:
        icon: 'activity'
        color: 'orange'