name: Reformat python files

on: [pull_request]


jobs:
  reformat-code:
    name: Check style of python files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: repo
      - name: Checkout Action
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: action
      - name: Check and change
        uses: Parply/python-prettier@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
