name: Reformat python files

on: pull_request

jobs:
  reformat-code:
    name: Check style of python files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check and change
        uses: Parply/python-prettier@master
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          URL: ${{ github.event.issue.comments_url }}
          COMMENT: 'true'