name: Reformat python files

on: 
  pull_request:
    types: [opened, synchronize, reopened] 

jobs:
  reformat-code:
    name: Check style of python files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check and change
        uses: Parply/python-prettier@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}